<h3 class="page-header">Tabela de custo</h3>

<form method="post">
	<div class="row">
	 	<input type="hidden" id="idExcluir">

		<div class="form-group col-md-3">
			<label for="produto">Produto</label> 
			<select class="form-control" name="produto" required>
				<option value="" <?php ($this->custo != null && $this->custo->getProduto() == '')? 'Selected' : '' ;?>>- Selecione -</option>
				<option value="Super Max" <?php if($this->custo != null && $this->custo->getProduto() == 'Super Max')echo 'selected';?>>Super Max</option>
				<option value="Max" <?php if($this->custo != null && $this->custo->getProduto() == 'Max')echo 'selected';?>>Max</option>
				<option value="Coppo Venetto" <?php if($this->custo != null && $this->custo->getProduto() == 'Coppo Venetto')echo 'selected';?>>Coppo Venetto</option>
				<option value="Fit" <?php if($this->custo != null && $this->custo->getProduto() == 'Fit')echo 'selected';?>>Fit</option>
				<option value="Espigão" <?php if($this->custo != null && $this->custo->getProduto() == 'Espigão')echo 'selected';?>>Espigão</option>
				<option value="Inicial" <?php if($this->custo != null && $this->custo->getProduto() == 'Inicial')echo 'selected';?>>Inicial</option>
				<option value="03 vias" <?php if($this->custo != null && $this->custo->getProduto() == '03 vias')echo 'selected';?>>03 vias</option>
				<option value="04 vias" <?php if($this->custo != null && $this->custo->getProduto() == '04 vias')echo 'selected';?>>04 vias</option>
				<option value="Capa Lateral" <?php if($this->custo != null && $this->custo->getProduto() == 'Capa Lateral')echo 'selected';?>>Capa Lateral</option>
				<option value="Policarbonato Max" <?php if($this->custo != null && $this->custo->getProduto() == 'Policarbonato Max')echo 'selected';?>>Policarbonato Max</option>
				<option value="Policabornato Coppo" <?php if($this->custo != null && $this->custo->getProduto() == 'Policabornato Coppo')echo 'selected';?>>Policabornato Coppo</option>
				<option value="Policabornato Fit" <?php if($this->custo != null && $this->custo->getProduto() == 'Policabornato Fit')echo 'selected';?>>Policabornato Fit</option>
				<option value="Manta Termica" <?php if($this->custo != null && $this->custo->getProduto() == 'Manta Termica')echo 'selected';?>>Manta Termica</option>
				<option value="Frete" <?php if($this->custo != null && $this->custo->getProduto() == 'Frete')echo 'selected';?>>Frete</option>
			</select>
		</div>
		
		<div class="form-group col-md-2">
			<label for="cor">Cor</label> 
			<select class="form-control" name="cor" required>
				<option value="" <?php echo ($this->custo != null && $this->custo->getCor() == '')? 'Selected' : '' ;?>>- Selecione -</option>
				<option value="Cinza Pérola" <?php echo ($this->custo != null && $this->custo->getCor() == 'Cinza Pérola')? 'Selected' : '' ;?>>Cinza Pérola</option>
				<option value="Grafite" <?php echo ($this->custo != null && $this->custo->getCor() == 'Grafite')? 'Selected' : '' ;?>>Grafite</option>
				<option value="Ocre" <?php echo ($this->custo != null && $this->custo->getCor() == 'Ocre')? 'Selected' : '' ;?>>Ocre</option>
				<option value="Marrom" <?php echo ($this->custo != null && $this->custo->getCor() == 'Marrom')? 'Selected' : '' ;?>>Marrom</option>
				<option value="Mostarda" <?php echo ($this->custo != null && $this->custo->getCor() == 'Mostarda')? 'Selected' : '' ;?>>Mostarda</option>
				<option value="Vermelha" <?php echo ($this->custo != null && $this->custo->getCor() == 'Vermelha')? 'Selected' : '' ;?>>Vermelha</option>
				<option value="Salmão" <?php echo ($this->custo != null && $this->custo->getCor() == 'Salmão')? 'Selected' : '' ;?>>Salmão</option>
			</select>
		</div>

		<div class="form-group col-md-2 has-feedback">
			<label for="data">Custo a vista</label>
			<input type="text" class="form-control valor" name="vista" required placeholder="Informe o Custo a vista" data-thousands="." data-decimal="," <?php echo $this->custo != null ? " value=\" ". $this->custo->getAvista()."\"" : ""?>>
		</div>
		
		<div class="form-group col-md-2 has-feedback">
			<label for="data">Custo a prazo</label>
			<input type="text" class="form-control valor" name="prazo" required placeholder="Informe o Custo a prazo" data-thousands="." data-decimal="," <?php echo $this->custo != null ? " value=\" ". $this->custo->getAprazo()."\"" : ""?>>
		</div>
	</div>

	<hr />

	<div class="row">
		<div class="col-md-12">
			<button type="submit" class="btn btn-primary pull-right">Salvar</button>
			<button type="button" onclick="window.history.back();" class="btn btn-default pull-right">Cancelar</button>
		</div>
	</div>
</form>

<div id="top" class="row">
	<div class="col-sm-3">
		<h2>Custo Cadastrado</h2>
	</div>
</div>

<!-- /#top -->

<hr />

<div id="list" class="row">
	<div class="table-responsive col-md-12">
		<table class="table table-striped" cellspacing="0" cellpadding="0" id="lista_custo">
			<thead>
				<tr>
					<th>produto</th>
					<th>Cor</th>
					<th>Custo a vista</th>
					<th>Custo a prazo</th>
					<th>Data do cadastro</th>
					<th>Ações</th>
				</tr>
			</thead>
			<tbody>
			     <?php foreach ($this->lista as $f): ?>
                 <tr>
					<td><?=$f->getProduto()?></td>
					<td><?=$f->getCor()?></td>
					<td><?=$f->getAvista()?></td>
					<td><?=$f->getAprazo()?></td>
					<th><?=$f->getData()?></th>
					<td class="actions">
						<a class="btn btn-warning btn-xs" href="<?php echo $this->url('custo', array('action' => 'custo', 'id' => $f->getId())); ?>">Editar</a> 
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal" onclick="enviarId(<?php echo $f->getId();?>)">Excluir</a>
					</td>
				</tr>
                <?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<!-- /#list -->


<!-- Modal -->

<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
					<span aria-hidden="true">&times;</span>
				</button>
				<h4 class="modal-title" id="modalLabel">Excluir Item</h4>
			</div>
			<div class="modal-body">Deseja realmente excluir este item?</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" id="excluir">Sim</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Não</button>
			</div>
		</div>
	</div>
</div>

<script>
	$(document).ready(function () {
		$(".valor").maskMoney();

		$('#lista_custo').DataTable({
    		"language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
    		}
		});

		$('#excluir').click(function(){
    		$.post( "<?php echo $this->url('excluircusto', array('action' => 'excluircusto')); ?>/"+$("#idExcluir").val(), function( data ) {
     			$('#delete-modal').modal('toggle');
     			
   		  		alert("Excluido com sucesso!");
				window.location = "<?php echo $this->url('custo'); ?>";
    		});
		});
	});

	function enviarId(id){
		$("#idExcluir").val(id);
	}
</script>