<div id="msg">

</div>



<div id="top" class="row">

	<div class="col-sm-3">

		<h2>Listar Vendas</h2>

	</div>

	<div class="col-sm-6"></div>

	<div class="col-sm-3">

		<a href="<?= $this->url('cadastrar'); ?>"

			class="btn btn-primary pull-right h2">Nova Vendas</a>

	</div>

</div>

<!-- /#top -->

<hr />

<div id="list" class="row">

<input type="hidden" id="idExcluir">

	<div class="table-responsive col-md-12">

		<table class="table table-striped" cellspacing="0" cellpadding="0" id="lista_vendas">

			<thead>
				<tr>
					<th>ID</th>
					<th>Data</th>
					<th>Cliente</th>
					<th>Forma Pagamento</th>
					<th>Data Entrega</th>
					<th class="actions">Ações</th>
				</tr>
			</thead>
			<tbody>

			      <?php foreach ($this->lista as $f): ?>
                  <tr>
					<td><?php echo $f->getId(); ?></td>
					<td><?php echo $f->getData(); ?></td>
					<td><?php echo $f->getCliente()->nome; ?></td>
					<td><?php echo $f->getForma_Pagamento()==1?'À Vista':'À prazo'; ?></td>
					<td><?php echo $f->getData_entrega(); ?></td>
					<td class="actions">
						<!--<a class="btn btn-success btn-xs" href="<?php echo $this->url('visualizar', array('action' => 'visualizar', 'id' => $f->getId())); ?>">Visualizar</a>--> 
						<a class="btn btn-warning btn-xs" href="<?php echo $this->url('cadastrar', array('action' => 'cadastrar', 'id' => $f->getId())); ?>">Editar</a> 
						<a class="btn btn-danger btn-xs" href="#" data-toggle="modal" data-target="#delete-modal" onclick="enviarId(<?php echo $f->getId();?>)">Excluir</a>
					</td>
				</tr>
                <?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<!-- /#list -->


<!-- Modal -->

<div class="modal fade" id="delete-modal" tabindex="-1" role="dialog"

	aria-labelledby="modalLabel">

	<div class="modal-dialog" role="document">

		<div class="modal-content">

			<div class="modal-header">

				<button type="button" class="close" data-dismiss="modal"

					aria-label="Fechar">

					<span aria-hidden="true">&times;</span>

				</button>

				<h4 class="modal-title" id="modalLabel">Excluir Item</h4>

			</div>

			<div class="modal-body">Deseja realmente excluir este item?</div>

			<div class="modal-footer">

				<button type="button" class="btn btn-primary" id="excluir">Sim</button>

				<button type="button" class="btn btn-default" data-dismiss="modal">Não</button>

			</div>

		</div>

	</div>

</div>

<script type="text/javascript">



function enviarId(id){

	$("#idExcluir").val(id);

}



$(document).ready( function () {

    $('#lista_vendas').DataTable({
		"order": [[ 0, "desc" ]],
    	"language": {
            "url": "https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json"
    	}
    });


    $('#excluir').click(function(){
    	$.post( "<?php echo $this->url('excluir', array('action' => 'excluir')); ?>/"+$("#idExcluir").val(), function( data ) {
     		$('#delete-modal').modal('toggle');
     		window.location.reload();
   		  	$( "#msg" ).addClass("alert alert-success").text("Excluido com sucesso!");
    	});
    });
});

</script>